import { useEffect, useState } from "react";
import Head from "next/head";
import WordGrid from "../components/WordGrid";
import styles from "../styles/Home.module.css";

export default function Home() {
    const [guessedWord, setGuessedWord] = useState([]),
        allowedLetters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"];

    useEffect(() => {
        document.addEventListener("keydown", function (event) {
            // let tempWord = [...guessedWord];
            // if(guessedWord.length < 5 && allowedLetters.includes(event.key.toUpperCase())) {
            //   tempWord.push(event.key.toUpperCase());
            //   setGuessedWord(tempWord);
            // }
            // if(guessedWord.length > 0 && event.key === "Delete") {
            //   tempWord.pop();
            //   setGuessedWord(tempWord);
            // }
            console.log(event.key);
        });
    });

    useEffect(() => {
      console.log(guessedWord);
    }, [guessedWord]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Langle</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Hola, me llamo es Gregg.</h1>
                <p>{guessedWord.join('')}</p>
                <WordGrid word={guessedWord} />
            </main>
        </div>
    );
}
